version: '3.8'

services:
  smarttransit-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smarttransit_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    extra_hosts:
      - "host.docker.internal:host-gateway"
