version: '3.8'

services:
  smarttransit-backend:
    image: ${BACKEND_IMAGE}
    container_name: smarttransit_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
